# Raspberry Pi BSP - 5.10 Kernel

require linux-yocto-rpi.inc

FILESEXTRAPATHS_prepend := "${THISDIR}/linux-yocto-5.10:"

# Extra patches needed since RCPL 6 for compatibility with RPi older patches
SRC_URI += "file://0001-Revert-firmware-raspberrypi-Fix-a-leak-in-rpi_firmwa.patch"
SRC_URI += "file://0002-Revert-firmware-raspberrypi-Keep-count-of-all-consum.patch"

# Extra patch needed since RCPL 5 to keep compatibility with RPi drivers
SRC_URI += "file://0001-Revert-OF-DT-Overlay-configfs-interface-v7.patch"

SRC_URI += "file://0001-arm-partially-revert-702b94bff3c50542a6e4ab9a4f4cef0.patch"
SRC_URI += "file://0002-Revert-rtc-pcf8523-properly-handle-oscillator-stop-b.patch"
SRC_URI += "file://0003-Revert-staging-bcm2835-audio-Drop-DT-dependency.patch"
SRC_URI += "file://0004-Revert-spi-spidev-Fix-CS-polarity-if-GPIO-descriptor.patch"
SRC_URI += "file://0005-Revert-mailbox-avoid-timer-start-from-callback.patch"
SRC_URI += "file://0006-smsx95xx-fix-crimes-against-truesize.patch"
SRC_URI += "file://0007-smsc95xx-Experimental-Enable-turbo_mode-and-packetsi.patch"
SRC_URI += "file://0008-Allow-mac-address-to-be-set-in-smsc95xx.patch"
SRC_URI += "file://0009-Protect-__release_resource-against-resources-without.patch"
SRC_URI += "file://0010-irq-bcm2836-Avoid-Invalid-trigger-warning.patch"
SRC_URI += "file://0011-irqchip-bcm2835-Add-FIQ-support.patch"
SRC_URI += "file://0012-irqchip-irq-bcm2835-Add-2836-FIQ-support.patch"
SRC_URI += "file://0013-spi-spidev-Completely-disable-the-spidev-warning.patch"
SRC_URI += "file://0014-dmaengine-bcm2835-Load-driver-early-and-support-lega.patch"
SRC_URI += "file://0015-firmware-Updated-mailbox-header.patch"
SRC_URI += "file://0016-rtc-Add-SPI-alias-for-pcf2123-driver.patch"
SRC_URI += "file://0017-watchdog-bcm2835-Support-setting-reboot-partition.patch"
SRC_URI += "file://0018-reboot-Use-power-off-rather-than-busy-spinning-when-.patch"
SRC_URI += "file://0019-bcm-Make-RASPBERRYPI_POWER-depend-on-PM.patch"
SRC_URI += "file://0020-Register-the-clocks-early-during-the-boot-process-so.patch"
SRC_URI += "file://0021-bcm2835-rng-Avoid-initialising-if-already-enabled.patch"
SRC_URI += "file://0022-clk-bcm2835-Mark-used-PLLs-and-dividers-CRITICAL.patch"
SRC_URI += "file://0023-clk-bcm2835-Add-claim-clocks-property.patch"
SRC_URI += "file://0024-clk-bcm2835-Read-max-core-clock-from-firmware.patch"
SRC_URI += "file://0025-sound-Demote-deferral-errors-to-INFO-level.patch"
SRC_URI += "file://0026-Update-vfpmodule.c.patch"
SRC_URI += "file://0027-i2c-bcm2835-Add-debug-support.patch"
SRC_URI += "file://0028-mm-Remove-the-PFN-busy-warning.patch"
SRC_URI += "file://0029-irqchip-irq-bcm2836-Remove-regmap-and-syscon-use.patch"
SRC_URI += "file://0030-lan78xx-Enable-LEDs-and-auto-negotiation.patch"
SRC_URI += "file://0031-amba_pl011-Don-t-use-DT-aliases-for-numbering.patch"
SRC_URI += "file://0032-amba_pl011-Round-input-clock-up.patch"
SRC_URI += "file://0033-amba_pl011-Insert-mb-for-correct-FIFO-handling.patch"
SRC_URI += "file://0034-amba_pl011-Add-cts-event-workaround-DT-property.patch"
SRC_URI += "file://0035-tty-amba-pl011-Make-TX-optimisation-conditional.patch"
SRC_URI += "file://0036-tty-amba-pl011-Add-un-throttle-support.patch"
SRC_URI += "file://0037-tty-amba-pl011-Avoid-rare-write-when-full-error.patch"
SRC_URI += "file://0038-pinctrl-bcm2835-Set-base-to-0-give-expected-gpio-num.patch"
SRC_URI += "file://0039-Main-bcm2708-bcm2709-linux-port.patch"
SRC_URI += "file://0040-Add-dwc_otg-driver.patch"
SRC_URI += "file://0041-bcm2708-framebuffer-driver.patch"
SRC_URI += "file://0042-Pulled-in-the-multi-frame-buffer-support-from-the-Pi.patch"
SRC_URI += "file://0043-fbdev-add-FBIOCOPYAREA-ioctl.patch"
SRC_URI += "file://0044-Speed-up-console-framebuffer-imageblit-function.patch"
SRC_URI += "file://0045-dmaengine-Add-support-for-BCM2708.patch"
SRC_URI += "file://0046-MMC-added-alternative-MMC-driver.patch"
SRC_URI += "file://0047-Adding-bcm2835-sdhost-driver-and-an-overlay-to-enabl.patch"
SRC_URI += "file://0048-vc_mem-Add-vc_mem-driver-for-querying-firmware-memor.patch"
SRC_URI += "file://0049-Add-dev-gpiomem-device-for-rootless-user-GPIO-access.patch"
SRC_URI += "file://0050-Add-SMI-driver.patch"
SRC_URI += "file://0051-Add-Chris-Boot-s-i2c-driver.patch"
SRC_URI += "file://0052-char-broadcom-Add-vcio-module.patch"
SRC_URI += "file://0053-firmware-bcm2835-Support-ARCH_BCM270x.patch"
SRC_URI += "file://0054-BCM2708-Add-core-Device-Tree-support.patch"
SRC_URI += "file://0055-BCM270x_DT-Add-pwr_led-and-the-required-input-trigge.patch"
SRC_URI += "file://0056-Added-Device-IDs-for-August-DVB-T-205.patch"
SRC_URI += "file://0057-Improve-__copy_to_user-and-__copy_from_user-performa.patch"
SRC_URI += "file://0058-gpio-poweroff-Allow-it-to-work-on-Raspberry-Pi.patch"
SRC_URI += "file://0059-mfd-Add-Raspberry-Pi-Sense-HAT-core-driver.patch"
SRC_URI += "file://0060-Add-support-for-all-the-downstream-rpi-sound-card-dr.patch"
SRC_URI += "file://0061-Fixes-a-problem-when-module-probes-before-i2c-module.patch"
SRC_URI += "file://0062-rpi_display-add-backlight-driver-and-overlay.patch"
SRC_URI += "file://0063-bcm2835-virtgpio-Virtual-GPIO-driver.patch"
SRC_URI += "file://0064-OF-DT-Overlay-configfs-interface.patch"
SRC_URI += "file://0065-brcm-adds-support-for-BCM43341-wifi.patch"
SRC_URI += "file://0066-hci_h5-Don-t-send-conf_req-when-ACTIVE.patch"
SRC_URI += "file://0067-config-Add-default-configs.patch"
SRC_URI += "file://0068-ARM64-Round-Robin-dispatch-IRQs-between-CPUs.patch"
SRC_URI += "file://0069-ARM64-Force-hardware-emulation-of-deprecated-instruc.patch"
SRC_URI += "file://0070-cache-export-clean-and-invalidate.patch"
SRC_URI += "file://0071-AXI-performance-monitor-driver-2222.patch"

# The following patch does mnot apply since RCPL 3. Commit
# 5ca472d40e2daebbfd926701902debcab0bbd15c changes how dis/enable is done.
# If this is a problem in future then this may need reworking.
#SRC_URI += "file://0072-cgroup-Disable-cgroup-memory-by-default.patch"

SRC_URI += "file://0073-ARM-bcm2835-Set-Serial-number-and-Revision.patch"
SRC_URI += "file://0074-dwc-otg-FIQ-Fix-bad-mode-in-data-abort-handler.patch"
SRC_URI += "file://0075-ARM-Activate-FIQs-to-avoid-__irq_startup-warnings.patch"
SRC_URI += "file://0076-raspberrypi-firmware-Export-the-general-transaction-.patch"
SRC_URI += "file://0077-i2c-gpio-Also-set-bus-numbers-from-reg-property.patch"
SRC_URI += "file://0078-added-capture_clear-option-to-pps-gpio-via-dtoverlay.patch"
SRC_URI += "file://0079-lan78xx-Read-initial-EEE-status-from-DT.patch"
SRC_URI += "file://0080-hid-Reduce-default-mouse-polling-interval-to-60Hz.patch"
SRC_URI += "file://0081-Add-ability-to-export-gpio-used-by-gpio-poweroff.patch"
SRC_URI += "file://0082-firmware-raspberrypi-Notify-firmware-of-a-reboot.patch"
SRC_URI += "file://0083-irqchip-irq-bcm2835-Calc.-FIQ_START-at-boot-time.patch"
SRC_URI += "file://0084-of-configfs-Use-of_overlay_fdt_apply-API-call.patch"
SRC_URI += "file://0085-net-lan78xx-Disable-TCP-Segmentation-Offload-TSO.patch"
SRC_URI += "file://0086-brcmfmac-Re-enable-firmware-roaming-support.patch"
SRC_URI += "file://0087-lan78xx-Move-enabling-of-EEE-into-PHY-init-code.patch"
SRC_URI += "file://0088-Add-rpi-poe-fan-driver.patch"
SRC_URI += "file://0089-cxd2880-CXD2880_SPI_DRV-should-select-DVB_CXD2880-wi.patch"
SRC_URI += "file://0090-hwmon-raspberrypi-Prevent-voltage-low-warnings-from-.patch"
SRC_URI += "file://0091-firmware-raspberrypi-Add-backward-compatible-get_thr.patch"
SRC_URI += "file://0092-sc16is7xx-Don-t-spin-if-no-data-received.patch"
SRC_URI += "file://0093-drivers-thermal-step_wise-add-support-for-hysteresis.patch"
SRC_URI += "file://0094-drivers-thermal-step_wise-avoid-throttling-at-hyster.patch"
SRC_URI += "file://0095-Update-issue-templates-2736.patch"
SRC_URI += "file://0096-net-lan78xx-Support-auto-downshift-to-100Mb-s.patch"
SRC_URI += "file://0097-firmware-raspberrypi-Report-the-fw-variant-during-pr.patch"
SRC_URI += "file://0098-lan78xx-Debounce-link-events-to-minimize-poll-storm.patch"
SRC_URI += "file://0099-lan78xx-EEE-support-is-now-a-PHY-property.patch"
SRC_URI += "file://0100-bcm2835-dma-Add-support-for-per-channel-flags.patch"
SRC_URI += "file://0101-rtc-rv3028-Add-backup-switchover-mode-support.patch"
SRC_URI += "file://0102-lan78xx-use-default-alignment-for-rx-buffers.patch"
SRC_URI += "file://0103-media-ov5647-Add-set_fmt-and-get_fmt-calls.patch"
SRC_URI += "file://0104-media-ov5647-Add-support-for-PWDN-GPIO.patch"
SRC_URI += "file://0105-media-ov5647-Add-support-for-non-continuous-clock-mo.patch"
SRC_URI += "file://0106-media-tc358743-Increase-FIFO-level-to-374.patch"
SRC_URI += "file://0107-media-tc358743-fix-connected-active-CSI-2-lane-repor.patch"
SRC_URI += "file://0108-media-tc358743-Add-support-for-972Mbit-s-link-freq.patch"
SRC_URI += "file://0109-media-tc358743-Check-I2C-succeeded-during-probe.patch"
SRC_URI += "file://0110-media-adv7180-Default-to-the-first-valid-input.patch"
SRC_URI += "file://0111-media-adv7180-Add-YPrPb-support-for-ADV7282M.patch"
SRC_URI += "file://0112-media-videodev2-Add-helper-defines-for-printing-FOUR.patch"
SRC_URI += "file://0113-dt-bindings-Document-BCM283x-CSI2-CCP2-receiver.patch"
SRC_URI += "file://0114-MAINTAINERS-Add-entry-for-BCM2835-Unicam-driver.patch"
SRC_URI += "file://0115-media-tc358743-Return-an-appropriate-colorspace-from.patch"
SRC_URI += "file://0116-staging-mmal-vchiq-Avoid-use-of-bool-in-structures.patch"
SRC_URI += "file://0117-staging-mmal-vchiq-Add-support-for-event-callbacks.patch"
SRC_URI += "file://0118-staging-vc04_services-Support-sending-data-to-MMAL-p.patch"
SRC_URI += "file://0119-media-videobuf2-Allow-exporting-of-a-struct-dmabuf.patch"
SRC_URI += "file://0120-staging-mmal-vchiq-Fix-client_component-for-64-bit-k.patch"
SRC_URI += "file://0121-clk-clk-bcm2835-Use-zd-when-printing-size_t.patch"
SRC_URI += "file://0122-media-ov5647-Use-gpiod_set_value_cansleep.patch"
SRC_URI += "file://0123-staging-mmal_vchiq-Add-in-the-Bayer-encoding-formats.patch"
SRC_URI += "file://0124-staging-mmal-vchiq-Update-mmal_parameters.h-with-rec.patch"
SRC_URI += "file://0125-staging-mmal-vchiq-Free-the-event-context-for-contro.patch"
SRC_URI += "file://0126-staging-mmal-vchiq-Fix-memory-leak-in-error-path.patch"
SRC_URI += "file://0127-w1-w1-gpio-Make-GPIO-an-output-for-strong-pullup.patch"
SRC_URI += "file://0128-arm-bcm2835-Fix-FIQ-early-ioremap.patch"
SRC_URI += "file://0129-arm-bcm2835-DMA-can-only-address-1GB.patch"
SRC_URI += "file://0130-hwrng-iproc-rng200-Add-BCM2838-support.patch"
SRC_URI += "file://0131-mmc-sdhci-iproc-Fix-vmmc-regulators-on-iProc.patch"
SRC_URI += "file://0132-vchiq-Add-36-bit-address-support.patch"
SRC_URI += "file://0133-bcm2835-pcm.c-Support-multichannel-audio.patch"
SRC_URI += "file://0134-bcmgenet-constrain-max-DMA-burst-length.patch"
SRC_URI += "file://0135-bcmgenet-Better-coalescing-parameter-defaults.patch"
SRC_URI += "file://0136-net-genet-enable-link-energy-detect-powerdown-for-ex.patch"
SRC_URI += "file://0137-usb-xhci-Disable-the-XHCI-5-second-timeout.patch"
SRC_URI += "file://0138-spi-bcm2835-enable-shared-interrupt-support.patch"
SRC_URI += "file://0139-clk-bcm2835-Don-t-wait-for-pllh-lock.patch"
SRC_URI += "file://0140-soc-bcm-bcm2835-pm-Add-support-for-2711.patch"
SRC_URI += "file://0141-clk-bcm2835-Add-support-for-setting-leaf-clock-rates.patch"
SRC_URI += "file://0142-clk-bcm2835-Allow-reparenting-leaf-clocks-while-they.patch"
SRC_URI += "file://0143-usb-add-plumbing-for-updating-interrupt-endpoint-int.patch"
SRC_URI += "file://0144-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch"
SRC_URI += "file://0145-usbhid-call-usb_fixup_endpoint-after-mangling-interv.patch"
SRC_URI += "file://0146-arm-bcm2835-Add-bcm2838-compatible-string.patch"
SRC_URI += "file://0147-drm-v3d-Add-support-for-2711.patch"
SRC_URI += "file://0148-drm-v3d-Skip-MMU-flush-if-the-device-is-currently-of.patch"
SRC_URI += "file://0149-drm-v3d-Hook-up-the-runtime-PM-ops.patch"
SRC_URI += "file://0150-xhci-add-quirk-for-host-controllers-that-don-t-updat.patch"
SRC_URI += "file://0151-i2c-bcm2835-Set-clock-stretch-timeout-to-35ms.patch"
SRC_URI += "file://0152-clk-bcm2835-Avoid-null-pointer-exception.patch"
SRC_URI += "file://0153-drm-v3d-HACK-gut-runtime-pm-for-now.patch"
SRC_URI += "file://0154-drm-v3d-Clock-V3D-down-when-not-in-use.patch"
SRC_URI += "file://0155-drivers-char-add-chardev-for-mmap-ing-the-RPiVid-con.patch"
SRC_URI += "file://0156-hid-usb-Add-device-quirks-for-Freeway-Airmouse-T3-an.patch"
SRC_URI += "file://0157-Add-HDMI1-facility-to-the-driver.patch"
SRC_URI += "file://0158-net-bcmgenet-Workaround-2-for-Pi4-Ethernet-fail.patch"
SRC_URI += "file://0159-xhci-Use-more-event-ring-segment-table-entries.patch"
SRC_URI += "file://0160-configs-arm64-bcm2711-Enable-V3D.patch"
SRC_URI += "file://0161-arch-arm-Add-model-string-to-cpuinfo.patch"
SRC_URI += "file://0162-arch-arm64-Add-Revision-Serial-Model-to-cpuinfo.patch"
SRC_URI += "file://0163-media-dt-bindings-Add-binding-for-the-Sony-IMX219-se.patch"
SRC_URI += "file://0164-v4l2-Add-a-Greyworld-AWB-mode.patch"
SRC_URI += "file://0165-staging-bcm2835-camera-Add-greyworld-AWB-mode.patch"
SRC_URI += "file://0166-drm-v3d-Delete-pm_runtime-support.patch"
SRC_URI += "file://0167-kbuild-Allow-.dtbo-overlays-to-be-built-piecemeal.patch"
SRC_URI += "file://0168-ARM-bcm-Switch-board-clk-and-pinctrl-to-bcm2711-comp.patch"
SRC_URI += "file://0169-Rename-HDMI-ALSA-device-names-check-for-enable-state.patch"
SRC_URI += "file://0170-dt-bindings-Add-binding-for-the-Infineon-IRS1125-sen.patch"
SRC_URI += "file://0171-media-i2c-Add-a-driver-for-the-Infineon-IRS1125-dept.patch"
SRC_URI += "file://0172-drm-v3d-Don-t-clear-MMU-control-bits-on-exception.patch"
SRC_URI += "file://0173-drm-v3d-Suppress-all-but-the-first-MMU-error.patch"
SRC_URI += "file://0174-drm-v3d-Plug-dma_fence-leak.patch"
SRC_URI += "file://0175-staging-vchiq_arm-Register-vcsm-cma-as-a-platform-dr.patch"
SRC_URI += "file://0176-staging-vchiq_arm-Register-bcm2835-codec-as-a-platfo.patch"
SRC_URI += "file://0177-net-bcmgenet-The-second-IRQ-is-optional.patch"
SRC_URI += "file://0178-net-phy-2711-Allow-ethernet-LED-mode-to-be-set-via-d.patch"
SRC_URI += "file://0179-net-phy-2711-Change-the-default-ethernet-LED-actions.patch"
SRC_URI += "file://0180-v3d_drv-Handle-missing-clock-more-gracefully.patch"
SRC_URI += "file://0181-v3d_gem-Kick-the-clock-so-firmware-knows-we-are-usin.patch"
SRC_URI += "file://0182-clk-raspberrypi-Allow-cpufreq-driver-to-also-adjust-.patch"
SRC_URI += "file://0183-clk-bcm2835-Disable-v3d-clock.patch"
SRC_URI += "file://0184-drm-v3d-Set-dma_mask-as-well-as-coherent_dma_mask.patch"
SRC_URI += "file://0185-staging-vchiq_arm-Set-up-dma-ranges-on-child-devices.patch"
SRC_URI += "file://0186-staging-vchiq-Use-the-old-dma-controller-for-OF-conf.patch"
SRC_URI += "file://0187-ARM-bcm-Backport-BCM2711-support-from-upstream.patch"
SRC_URI += "file://0188-Initialise-rpi-firmware-before-clk-bcm2835.patch"
SRC_URI += "file://0189-staging-vchiq_arm-Give-vchiq-children-DT-nodes.patch"
SRC_URI += "file://0190-pinctrl-bcm2835-Remove-gpiochip-on-error.patch"
SRC_URI += "file://0191-pinctrl-bcm2835-Change-init-order-for-gpio-hogs.patch"
SRC_URI += "file://0192-pinctrl-bcm2835-Accept-fewer-than-expected-IRQs.patch"
SRC_URI += "file://0193-drivers-char-vcio-Use-common-compat-header.patch"
SRC_URI += "file://0194-video-fbdev-bcm2708_fb-Use-common-compat-header.patch"
SRC_URI += "file://0195-of-overlay-Correct-symbol-path-fixups.patch"
SRC_URI += "file://0196-dt-bindings-pci-Add-DT-docs-for-Brcmstb-PCIe-device.patch"
SRC_URI += "file://0197-Kbuild-Allow-.dtbo-overlays-to-be-built-adjust.patch"
SRC_URI += "file://0198-bcmgenet-Disable-skip_umac_reset-by-default.patch"
SRC_URI += "file://0199-drm-fourcc-Add-packed-10bit-YUV-4-2-0-format.patch"
SRC_URI += "file://0200-media-uapi-hevc-Add-scaling-matrix-control.patch"
SRC_URI += "file://0201-media-uapi-hevc-Add-segment-address-field.patch"

# The following patch is not needed since RCPL 4
#SRC_URI += "file://0202-media-hevc_ctrls-Add-slice-param-dependent-slice-seg.patch"

SRC_URI += "file://0203-media-uapi-Add-hevc-ctrls-for-WPP-decoding.patch"
SRC_URI += "file://0204-media-videodev2.h-Add-a-format-for-column-YUV4-2-0-m.patch"
SRC_URI += "file://0205-media-v4l2-mem2mem-allow-request-job-buffer-processi.patch"
SRC_URI += "file://0206-media-dt-bindings-media-Add-binding-for-the-Raspberr.patch"
SRC_URI += "file://0207-staging-media-Add-Raspberry-Pi-V4L2-H265-decoder.patch"
SRC_URI += "file://0208-mmc-sdhci-Silence-MMC-warnings.patch"
SRC_URI += "file://0209-dt-bindings-clock-Add-a-binding-for-the-RPi-Firmware.patch"
SRC_URI += "file://0210-dt-bindings-display-vc4-hdmi-Add-BCM2711-HDMI-contro.patch"
SRC_URI += "file://0211-drm-Checking-of-the-pitch-is-only-valid-for-linear-f.patch"
SRC_URI += "file://0212-overlays-Fix-dtc-warnings-in-i2c-gpio.patch"
SRC_URI += "file://0213-driver-char-rpivid-Remove-legacy-name-support.patch"
SRC_URI += "file://0214-spi-Force-CS_HIGH-if-GPIO-descriptors-are-used.patch"
SRC_URI += "file://0215-driver-char-rpivid-Don-t-map-more-than-wanted.patch"
SRC_URI += "file://0216-media-bcm2835-unicam-Driver-for-CCP2-CSI2-camera-int.patch"
SRC_URI += "file://0217-media-uapi-v4l2-core-Add-sensor-ancillary-data-V4L2-.patch"
SRC_URI += "file://0218-media-uapi-Add-MEDIA_BUS_FMT_SENSOR_DATA-media-bus-f.patch"
SRC_URI += "file://0219-media-bcm2835-unicam-Add-support-for-mulitple-device.patch"
SRC_URI += "file://0220-media-bcm2835-unicam-Add-embedded-data-node.patch"
SRC_URI += "file://0221-media-bcm2835-unicam-Use-dummy-buffer-if-none-have-b.patch"
SRC_URI += "file://0222-media-bcm2835-unicam-Disable-event-related-ioctls-on.patch"
SRC_URI += "file://0223-media-bcm2835-unicam-Add-support-for-the-FRAME_SYNC-.patch"
SRC_URI += "file://0224-media-imx219-Advertise-embedded-data-node-on-media-p.patch"
SRC_URI += "file://0225-media-bcm2835-unicam-Re-fetch-mbus-code-from-subdev-.patch"
SRC_URI += "file://0226-media-uapi-v4l2-core-Add-ISP-statistics-output-V4L2-.patch"
SRC_URI += "file://0227-media-uapi-v4l-ctrls-Add-CID-base-for-the-bcm2835-is.patch"
SRC_URI += "file://0228-staging-vchiq-Load-bcm2835_isp-driver-from-vchiq.patch"
SRC_URI += "file://0229-bcm2835-dma-Add-proper-40-bit-DMA-support.patch"
SRC_URI += "file://0230-overlays-Make-the-i2c-gpio-overlay-safe-again.patch"
SRC_URI += "file://0231-media-i2c-imx219-Declare-that-the-driver-can-create-.patch"
SRC_URI += "file://0232-media-ov5647-Fix-return-codes-from-ov5647_write-ov56.patch"
SRC_URI += "file://0233-media-ov5647-Add-basic-support-for-multiple-sensor-m.patch"
SRC_URI += "file://0234-media-ov5647-Add-V4L2-controls-for-analogue-gain-exp.patch"
SRC_URI += "file://0235-media-ov5647-Add-extra-10-bit-sensor-modes.patch"
SRC_URI += "file://0236-media-ov5647-change-defaults-to-better-match-raw-cam.patch"
SRC_URI += "file://0237-media-i2c-ov5647-Add-support-for-g_selection-to-refl.patch"
SRC_URI += "file://0238-media-i2c-ov5467-Fixup-error-path-to-release-mutex.patch"
SRC_URI += "file://0239-media-i2c-ov5647-Support-V4L2_CID_PIXEL_RATE.patch"
SRC_URI += "file://0240-media-i2c-ov5647-Set-V4L2_SUBDEV_FL_HAS_EVENTS-flag.patch"
SRC_URI += "file://0241-media-i2c-ov5647-Add-support-for-V4L2_CID_VBLANK.patch"
SRC_URI += "file://0242-media-i2c-ov5647-Neither-analogue-gain-nor-exposure-.patch"
SRC_URI += "file://0243-media-i2c-ov5647-Use-member-names-in-mode-tables.patch"
SRC_URI += "file://0244-media-i2c-ov5647-Advertise-the-correct-exposure-rang.patch"
SRC_URI += "file://0245-media-bcm2835-unicam-Add-support-for-VIDIOC_-S-G-_SE.patch"
SRC_URI += "file://0246-media-bcm2835-unicam-Do-not-stop-streaming-in-unicam.patch"
SRC_URI += "file://0247-media-bcm2835-unicam-Fix-reference-counting-in-unica.patch"
SRC_URI += "file://0248-media-i2c-tc358743-Fix-fallthrough-warning.patch"
SRC_URI += "file://0249-media-bcm2835-unicam-Fix-uninitialized-warning.patch"
SRC_URI += "file://0250-video-bcm2708_fb-Disable-FB-if-no-displays-found.patch"
SRC_URI += "file://0251-dt-bindings-media-i2c-Add-IMX477-CMOS-sensor-binding.patch"
SRC_URI += "file://0252-media-bcm2835-unicam-Always-service-interrupts.patch"
SRC_URI += "file://0253-sc16is7xx-Fix-for-hardware-flow-control.patch"
SRC_URI += "file://0254-staging-vc04_services-mmal-vchiq-Update-parameters-l.patch"
SRC_URI += "file://0255-staging-vc04_services-bcm2835-camera-Request-headers.patch"
SRC_URI += "file://0256-kbuild-Disable-gcc-plugins.patch"
SRC_URI += "file://0257-media-bcm2835-unicam-Retain-packing-information-on-G.patch"
SRC_URI += "file://0258-zswap-Defer-zswap-initialisation.patch"
SRC_URI += "file://0259-SQUASH-pinctrl-bcm2835-Set-base-for-bcm2711-GPIO-to-.patch"
SRC_URI += "file://0260-staging-vchiq_arm-Clean-up-40-bit-DMA-support.patch"
SRC_URI += "file://0261-media-bcm2835-unicam-change-minimum-number-of-vb2_qu.patch"
SRC_URI += "file://0262-brcmfmac-BCM43436-needs-dedicated-firmware.patch"
SRC_URI += "file://0263-snd_bcm2835-disable-HDMI-audio-when-vc4-is-used-3640.patch"
SRC_URI += "file://0264-gpiolib-Don-t-prevent-IRQ-usage-of-output-GPIOs.patch"
SRC_URI += "file://0265-PCI-brcmstb-Add-DT-property-to-control-L1SS.patch"
SRC_URI += "file://0266-media-irs1125-Using-i2c_transfer-for-ic2-reads.patch"
SRC_URI += "file://0267-media-irs1125-Refactoring-and-debug-messages.patch"
SRC_URI += "file://0268-media-irs1125-Atomic-access-to-imager-reconfiguratio.patch"
SRC_URI += "file://0269-media-irs1125-Keep-HW-in-sync-after-imager-reset.patch"
SRC_URI += "file://0270-staging-bcm2835-audio-Add-missing-MODULE_ALIAS.patch"
SRC_URI += "file://0271-brcmfmac-Prefer-a-ccode-from-OTP-over-nvram-file.patch"
SRC_URI += "file://0272-drivers-media-Remove-the-downstream-version-of-bcm28.patch"
SRC_URI += "file://0273-media-bcm2835-unicam-Driver-for-CCP2-CSI2-camera-int.patch"
SRC_URI += "file://0274-media-bcm2835-unicam-Add-support-for-get_mbus_config.patch"
SRC_URI += "file://0275-media-bcm2835-unicam-Avoid-gcc-warning-over-0-on-end.patch"
SRC_URI += "file://0276-media-i2c-imx290-set-the-format-before-VIDIOC_SUBDEV.patch"
SRC_URI += "file://0277-media-i2c-imx290-Add-support-for-74.25MHz-clock.patch"
SRC_URI += "file://0278-media-i2c-imx290-Correct-range-for-V4L2_CID_GAIN-to-.patch"
SRC_URI += "file://0279-media-i2c-imx290-Convert-HMAX-setting-into-V4L2_CID_.patch"
SRC_URI += "file://0280-media-i2c-imx290-Add-support-for-V4L2_CID_VBLANK.patch"
SRC_URI += "file://0281-media-i2c-imx290-Add-exposure-control-to-the-driver.patch"
SRC_URI += "file://0282-media-i2c-imx290-Add-H-and-V-flip-controls.patch"
SRC_URI += "file://0283-media-dt-bindings-media-i2c-Add-mono-version-to-IMX2.patch"
SRC_URI += "file://0284-media-i2c-imx290-Add-support-for-the-mono-sensor-var.patch"
SRC_URI += "file://0285-media-i2c-imx290-Switch-set_hmax-to-use-imx290_write.patch"
SRC_URI += "file://0286-serial-8250-bcm2835aux-defer-if-clock-is-zero.patch"
SRC_URI += "file://0287-media-Add-a-pixel-format-for-MIPI-packed-12bit-luma-.patch"
SRC_URI += "file://0288-media-Add-a-pixel-format-for-MIPI-packed-14bit-luma-.patch"
SRC_URI += "file://0289-media-bcm2835-unicam-Add-support-for-12bit-mono-pack.patch"
SRC_URI += "file://0290-media-bcm2835-unicam-Add-support-for-14bit-mono-sour.patch"
SRC_URI += "file://0291-media-bcm2835-unicam-Add-support-for-unpacked-14bit-.patch"
SRC_URI += "file://0292-bcm2835-dma-Add-NO_WAIT_RESP-flag.patch"
SRC_URI += "file://0293-media-i2c-add-ov9281-driver.patch"
SRC_URI += "file://0294-media-i2c-ov9281-fix-mclk-issue-when-probe-multiple-.patch"
SRC_URI += "file://0295-media-i2c-ov9281-add-enum_frame_interval-function-fo.patch"
SRC_URI += "file://0296-media-i2c-ov9281-Fixup-for-recent-kernel-releases-an.patch"
SRC_URI += "file://0297-media-i2c-ov9281-Read-chip-ID-via-2-reads.patch"
SRC_URI += "file://0298-media-i2c-imx290-Explicitly-set-v-h-blank-on-mode-ch.patch"
SRC_URI += "file://0299-media-i2c-imx290-Add-support-for-g_selection-to-repo.patch"
SRC_URI += "file://0300-media-i2c-imx290-Set-the-colorspace-fields-in-the-fo.patch"
SRC_URI += "file://0301-media-bcm2835-unicam-Reinstate-V4L2_CAP_READWRITE-in.patch"
SRC_URI += "file://0302-media-bcm2835-unicam-Ensure-type-is-VIDEO_CAPTURE-in.patch"
SRC_URI += "file://0303-media-bcm2835-unicam-Set-VPU-min-clock-freq-to-250Mh.patch"
SRC_URI += "file://0304-dt-bindings-bcm2835-unicam-Update-documentation-with.patch"
SRC_URI += "file://0305-media-i2c-ov5647-Parse-and-register-properties.patch"
SRC_URI += "file://0306-leds-Add-the-actpwr-trigger.patch"
SRC_URI += "file://0307-staging-vchiq_arm-children-inherit-DMA-config.patch"
SRC_URI += "file://0308-bcm2835-dma-Advertise-the-full-DMA-range.patch"
SRC_URI += "file://0309-ARM-proc-v7-Force-misalignment-of-early-stmia.patch"
SRC_URI += "file://0310-media-bcm2835-unicam-Select-MEDIA_CONTROLLER-and-VID.patch"
SRC_URI += "file://0311-staging-media-rpivid-Select-MEDIA_CONTROLLER-and-MED.patch"
SRC_URI += "file://0312-media-bcm2835-unicam-Drop-WARN-on-uing-direct-cache-.patch"
SRC_URI += "file://0313-media-i2c-tc358743-Only-allow-supported-pixel-fmts-i.patch"
SRC_URI += "file://0314-media-i2c-ov9281-Add-support-for-8-bit-readout.patch"
SRC_URI += "file://0315-bcm2835-mmc-uninitialized_var-is-no-more.patch"
SRC_URI += "file://0316-dwc_otg-whitelist_table-is-now-productlist_table.patch"
SRC_URI += "file://0317-vchiq_2835_arm-Implement-a-DMA-pool-for-small-bulk-t.patch"
SRC_URI += "file://0318-include-firmware-Add-enum-for-RPI_FIRMWARE_FRAMEBUFF.patch"
SRC_URI += "file://0319-vc4_hdmi-BCM2835-requires-a-fixed-hsm-clock-for-CEC-.patch"

# The following two patches are already included in WR kernel
#SRC_URI += "file://0320-vc4_hdmi-Fix-register-offset-when-sending-longer-CEC.patch"
#SRC_URI += "file://0321-vc4_hdmi-Fix-up-CEC-registers.patch"

SRC_URI += "file://0322-vc4_hdmi_regs-Add-Intr2-register-block.patch"
SRC_URI += "file://0323-vc4_hdmi_regs-Make-interrupt-mask-variant-specific.patch"
SRC_URI += "file://0324-vc4_hdmi-Make-irq-shared.patch"

# The following two patches don't apply, but are reverted by patches 0511 and
# 0512 anyway, so no need to fix them
#SRC_URI += "file://0325-vc4_hdmi-Adjust-CEC-ref-clock-based-on-its-input-clo.patch"
#SRC_URI += "file://0326-vc4_hdmi-Remove-cec_available-flag-as-always-support.patch"

SRC_URI += "file://0327-drm-vc4-Adopt-the-dma-configuration-from-the-HVS-or-.patch"

# The following patch is not needed since RCPL 6
#SRC_URI += "file://0328-vc4_hdmi-Set-HD_CTL_WHOLSMP-and-HD_CTL_CHALIGN_SET.patch"

SRC_URI += "file://0329-vc4_hdmi-Set-HDMI_MAI_FMT.patch"
SRC_URI += "file://0330-drm-vc4-add-iec958-controls-to-vc4_hdmi.patch"
SRC_URI += "file://0331-drm-vc4-move-setup-from-hw_params-to-prepare.patch"
SRC_URI += "file://0332-drm-vc4-enable-HBR-MAI-format-on-HBR-streams.patch"
SRC_URI += "file://0333-vc4_hdmi-Remove-firmware-logic-for-MAI-threshold-set.patch"
SRC_URI += "file://0334-vc_hdmi-Set-VC4_HDMI_MAI_CONFIG_FORMAT_REVERSE.patch"
SRC_URI += "file://0335-vc4-Report-channel-mapping-back-to-userspace.patch"

# The following patch does not apply on the WR kernel but is reverted by 0510 anyway
#SRC_URI += "file://0336-vc4-cec-Restore-cec-physical-address-on-reconnect.patch"

SRC_URI += "file://0337-drm-vc4-Add-support-for-DRM_FORMAT_P030-to-vc4-plane.patch"
SRC_URI += "file://0338-drm-vc4-Add-support-for-YUV-color-encodings-and-rang.patch"
SRC_URI += "file://0339-drm-vc4-Add-firmware-kms-mode.patch"
SRC_URI += "file://0340-drm-vc4-Add-FKMS-as-an-acceptable-node-for-dma-range.patch"
SRC_URI += "file://0341-media-i2c-Add-driver-for-Sony-IMX477-sensor.patch"
SRC_URI += "file://0342-media-i2c-imx477-Add-support-for-adaptive-frame-cont.patch"
SRC_URI += "file://0343-media-i2c-imx477-Return-correct-result-on-sensor-id-.patch"
SRC_URI += "file://0344-media-i2c-imx477-Parse-and-register-properties.patch"
SRC_URI += "file://0345-media-bcm2835-unicam-Always-service-interrupts.patch"
SRC_URI += "file://0346-media-bcm2835-unicam-Fix-uninitialized-warning.patch"
SRC_URI += "file://0347-media-bcm2835-unicam-Fixup-review-comments-from-Hans.patch"
SRC_URI += "file://0348-media-bcm2835-unicam-Retain-packing-information-on-G.patch"
SRC_URI += "file://0349-media-bcm2835-unicam-change-minimum-number-of-vb2_qu.patch"
SRC_URI += "file://0350-staging-fbtft-Add-support-for-display-variants.patch"
SRC_URI += "file://0351-brcmfmac-Increase-power-saving-delay-to-2s.patch"
SRC_URI += "file://0352-rpivid_h265-Fix-width-height-typo.patch"
SRC_URI += "file://0353-net-bcmgenet-Reset-RBUF-on-first-open.patch"
SRC_URI += "file://0354-char-Add-broadcom-char-drivers-back-to-build-files.patch"

# The following patch is not needed since RCPL 5
#SRC_URI += "file://0355-USB-gadget-f_hid-avoid-crashes-and-log-spam.patch"

SRC_URI += "file://0356-dwc_otg-initialise-sched_frame-for-periodic-QHs-that.patch"
SRC_URI += "file://0357-staging-bcm2835-camera-Replace-deprecated-V4L2_PIX_F.patch"
SRC_URI += "file://0358-staging-vc04_services-Add-new-vc-sm-cma-driver.patch"
SRC_URI += "file://0359-staging-vchiq-mmal-Add-support-for-14bit-Bayer.patch"
SRC_URI += "file://0360-staging-mmal-vchiq-Add-monochrome-image-formats.patch"
SRC_URI += "file://0361-staging-mmal-vchiq-Use-vc-sm-cma-to-support-zero-cop.patch"
SRC_URI += "file://0362-staging-vc04_services-Add-a-V4L2-M2M-codec-driver.patch"
SRC_URI += "file://0363-bcm2835-dma-only-reserve-channel-0-if-legacy-dma-dri.patch"
SRC_URI += "file://0364-uapi-bcm2835-isp-Add-bcm2835-isp-uapi-header-file.patch"
SRC_URI += "file://0365-staging-vc04_services-ISP-Add-a-more-complex-ISP-pro.patch"
SRC_URI += "file://0366-drm-vc4-A-present-but-empty-dmas-disables-audio.patch"
SRC_URI += "file://0367-drm-vc4-Add-debugfs-node-that-dumps-the-current-disp.patch"
SRC_URI += "file://0368-gpio-Add-gpio-fsm-driver.patch"

# The following patch does not apply on the WR kernel but is reverted by 0509 anyway
#SRC_URI += "file://0369-drm-vc4-Reading-the-hotplug-register-is-only-valid-i.patch"

SRC_URI += "file://0370-drm-vc4-Add-all-the-HDMI-registers-into-the-debugfs-.patch"
SRC_URI += "file://0371-ARM-dts-bcm271x-Use-a53-pmu-drop-RPI364.patch"
SRC_URI += "file://0372-overlays-Add-option-to-disable-composite-to-vc4-kms-.patch"
SRC_URI += "file://0373-overlays-imx219-Correct-link-frequency-to-match-the-.patch"
SRC_URI += "file://0374-dts-Add-CM4-to-arm64-dt-files.patch"
SRC_URI += "file://0375-drm-vc4-Add-the-2711-HVS-as-a-suitable-DMA-node.patch"
SRC_URI += "file://0376-xhci-quirks-add-link-TRB-quirk-for-VL805.patch"
SRC_URI += "file://0377-dts-Tidy-the-Raspberry-Pi-Makefile-entries.patch"
SRC_URI += "file://0378-staging-bcm2835-audio-Add-disable-headphones-flag.patch"
SRC_URI += "file://0379-ARM-dts-Disable-headphone-audio-on-Zeroes-CM4.patch"
SRC_URI += "file://0380-overlays-Enable-headphone-audio-in-audremap.patch"
SRC_URI += "file://0381-rpisense-fb-Set-pseudo_pallete-to-prevent-crash-on-f.patch"
SRC_URI += "file://0382-ARM-dts-Expand-PCIe-space-on-BCM2711.patch"
SRC_URI += "file://0383-configs-Set-RASPBERRYPI_FIRMWARE-for-arm64-bcm2711.patch"
SRC_URI += "file://0384-dwc_otg-Minimise-header-and-fix-build-warnings.patch"
SRC_URI += "file://0385-gpio-fsm-Fix-a-build-warning.patch"
SRC_URI += "file://0386-rpivid_h625-Fix-build-warnings.patch"
SRC_URI += "file://0387-bcm2708_fb-Fix-a-build-warning.patch"
SRC_URI += "file://0388-PiFi-40-defconfigs.patch"
SRC_URI += "file://0389-PiFi-40-Devicetree-files.patch"
SRC_URI += "file://0390-PiFi-40-driver-Makefile-and-Kconfig.patch"
SRC_URI += "file://0391-bcm2835-pcm-Fix-up-multichannel-pcm-audio.patch"
SRC_URI += "file://0392-watchdog-bcm2835-Ignore-params-after-the-partition-n.patch"
SRC_URI += "file://0393-firmware-raspberrypi-Add-support-for-tryonce-reboot-.patch"
SRC_URI += "file://0394-phy-broadcom-split-out-the-BCM54213PE-from-the-BCM54.patch"
SRC_URI += "file://0395-phy-broadcom-Add-bcm54213pe-configuration.patch"
SRC_URI += "file://0396-configs-Add-CONFIG_MAX31856-m.patch"
SRC_URI += "file://0397-overlays-Add-MAX31856-support-to-maxtherm-overlay.patch"
SRC_URI += "file://0398-ARM-dts-Add-bcm2711-rpi-400.dts.patch"
SRC_URI += "file://0399-overlays-Deprecate-and-delete-the-sdtweak-overlay.patch"
SRC_URI += "file://0400-ARM-dts-bcm27xx-Remove-enable_headphones-setting.patch"
SRC_URI += "file://0401-configs-Add-CAN_MCP251XFD-m-and-CAN_ISOTP-m.patch"
SRC_URI += "file://0402-vc4_hdmi-Report-that-3d-stereo-is-allowed.patch"
SRC_URI += "file://0403-PCI-brcmstb-Restore-initial-fundamental-reset.patch"
SRC_URI += "file://0404-vc4-Clear-unused-infoframe-packet-RAM-registers.patch"
SRC_URI += "file://0405-Input-edt-ft5x06-Poll-the-device-if-no-interrupt-is-.patch"
SRC_URI += "file://0406-dtoverlays-Add-an-overlay-for-the-EDT-FT5406-touchsc.patch"
SRC_URI += "file://0407-drm-panel-raspberrypi-touchscreen-Use-independent-I2.patch"
SRC_URI += "file://0408-drm-panel-raspberrypi-ts-Insert-delay-before-polling.patch"
SRC_URI += "file://0409-Add-devicetree-support-for-RaspberryPi-7-panel-over-.patch"
SRC_URI += "file://0410-mcp251xfd-add-overlay.patch"
SRC_URI += "file://0411-configs-Regenerate-the-defconfigs.patch"
SRC_URI += "file://0412-configs-Restore-BRIDGE_NETFILTER-m.patch"
SRC_URI += "file://0413-configs-Enable-WireGuard-kernel-module-on-armhf-conf.patch"
SRC_URI += "file://0414-media-ov9281-Add-1280x720-and-640x480-modes.patch"
SRC_URI += "file://0415-drm-vc4-Add-support-for-DSI0.patch"
SRC_URI += "file://0416-dt-bindings-Add-compatible-for-BCM2711-DSI1.patch"
SRC_URI += "file://0417-drm-vc4-Add-configuration-for-BCM2711-DSI1.patch"
SRC_URI += "file://0418-dt-Use-compatible-string-for-BCM2711-DSI1.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0419-vc4_hdmi-Move-hdmi-reset-to-bind.patch"

SRC_URI += "file://0420-drm-vc4-Correct-DSI-register-definition.patch"
SRC_URI += "file://0421-Allo-boss2-driver.patch"
SRC_URI += "file://0422-Add-allo-boss2-overlay.patch"
SRC_URI += "file://0423-Add-allo-boss2-config.patch"
SRC_URI += "file://0424-Overlay-Update-Allo-Piano-Plus-dac-driver-for-5.4.y-.patch"
SRC_URI += "file://0425-media-bcm2835-unicam-Correctly-handle-error-propagat.patch"
SRC_URI += "file://0426-media-bcm2835-unicam-Return-early-from-stop_streamin.patch"
SRC_URI += "file://0427-media-bcm2835-unicam-Clear-clock-state-when-stopping.patch"
SRC_URI += "file://0428-PCI-brcmstb-Advertise-MSI-X-support.patch"
SRC_URI += "file://0429-ARM-dts-CM4-audio-pins-are-not-connected.patch"
SRC_URI += "file://0430-configs-Add-RTC_DRV_PCF85063-m.patch"
SRC_URI += "file://0431-overlays-Add-PCF85063-and-PCF85063A-to-i2c-rtc.patch"
SRC_URI += "file://0432-overlays-Fix-cut-and-paste-error-in-README.patch"
SRC_URI += "file://0433-staging-bcm2835-codec-Ensure-OUTPUT-timestamps-are-a.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0434-Revert-media-videobuf2-Fix-length-check-for-single-p.patch"

SRC_URI += "file://0435-net-lan78xx-Ack-pending-PHY-ints-when-resetting.patch"
SRC_URI += "file://0436-overlays-mpu6050-Add-addr-parameter.patch"
SRC_URI += "file://0437-drm-vc4-Make-normalize_zpos-conditional-on-using-fkm.patch"
SRC_URI += "file://0438-overlays-Add-missing-addresses-to-ads1015-ads1115.patch"
SRC_URI += "file://0439-media-i2c-imx477-Selection-compliance-fixes.patch"
SRC_URI += "file://0440-staging-vc04_services-codec-Add-support-for-CID-MPEG.patch"
SRC_URI += "file://0441-staging-vc04_services-codec-Clear-last-buf-dequeued-.patch"
SRC_URI += "file://0442-drm-atomic-Pass-the-full-state-to-CRTC-atomic-enable.patch"
SRC_URI += "file://0443-drm-atomic-Pass-the-full-state-to-CRTC-atomic_check.patch"
SRC_URI += "file://0444-drm-atomic-Pass-the-full-state-to-CRTC-atomic-begin-.patch"
SRC_URI += "file://0445-drm-vc4-hvs-Align-the-HVS-atomic-hooks-to-the-new-AP.patch"
SRC_URI += "file://0446-drm-vc4-Pass-the-atomic-state-to-encoder-hooks.patch"
SRC_URI += "file://0447-drm-vc4-hdmi-Take-into-account-the-clock-doubling-fl.patch"
SRC_URI += "file://0448-drm-vc4-hdmi-Don-t-access-the-connector-state-in-res.patch"
SRC_URI += "file://0449-drm-vc4-hdmi-Create-a-custom-connector-state.patch"
SRC_URI += "file://0450-drm-vc4-hdmi-Store-pixel-frequency-in-the-connector-.patch"
SRC_URI += "file://0451-drm-vc4-hdmi-Use-the-connector-state-pixel-rate-for-.patch"

# The following patch does not apply on the WR kernel, but is reverted by 0507
# anyway, so no need to fix it
#SRC_URI += "file://0452-drm-vc4-hdmi-Limit-the-BCM2711-to-the-max-without-sc.patch"

SRC_URI += "file://0453-drm-vc4-hdmi-Enable-10-12-bpc-output.patch"
SRC_URI += "file://0454-drm-vc4-Fixup-fkms-for-API-change.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0455-staging-vchiq-Fix-bulk-userdata-handling.patch"

SRC_URI += "file://0456-overlays-Rebuild-upstream-with-latest-ovmerge.patch"
SRC_URI += "file://0457-Add-overlay-for-Seeed-Studio-CAN-BUS-FD-HAT-4034.patch"
SRC_URI += "file://0458-vc-sm-cma-fixed-kbuild-problem.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0459-staging-vchiq-Fix-bulk-transfers-on-64-bit-builds.patch"

SRC_URI += "file://0460-staging-vc04-services-codec-Fix-logical-precedence-i.patch"

# The following patch is not needed since RCPL 4
#SRC_URI += "file://0461-staging-mmal-vchiq-Fix-incorrect-static-vchiq_instan.patch"

SRC_URI += "file://0462-staging-vc04_services-Add-additional-unpacked-raw-fo.patch"
SRC_URI += "file://0463-staging-bcm2835-codec-Add-the-unpacked-16bpp-raw-for.patch"
SRC_URI += "file://0464-staging-bcm2835-codec-Log-the-number-of-excess-suppo.patch"
SRC_URI += "file://0465-staging-bcm2835-isp-Add-the-unpacked-16bpp-raw-forma.patch"
SRC_URI += "file://0466-staging-bcm2835-isp-Log-the-number-of-excess-support.patch"
SRC_URI += "file://0467-bcm2835-dma-Add-bcm2835-dma-Add-DMA_WIDE_SOURCE-and-.patch"
SRC_URI += "file://0468-bcm2835-dma-Move-WAIT_RESP-from-extra-to-info.patch"
SRC_URI += "file://0469-bcm2835-dma-Avoid-losing-CS-flags-after-interrupt.patch"
SRC_URI += "file://0470-dt-Enable-DMA_WIDE_SOURCE-and-DMA_WIDE_DEST-for-hdmi.patch"
SRC_URI += "file://0471-bcm2711-rpi.dtsi-Bump-hdmi-audio-dma-panic-priority-.patch"
SRC_URI += "file://0472-media-i2c-ov5647-Selection-compliance-fixes.patch"
SRC_URI += "file://0473-overlays-give-Seeed-Studio-CAN-BUS-FD-HAT-a-v2-postf.patch"
SRC_URI += "file://0474-overlays-Add-overlay-for-Seeed-Studio-CAN-BUS-FD-HAT.patch"
SRC_URI += "file://0475-overlays-add-wm8960-soundcard-overlay.patch"
SRC_URI += "file://0476-overlays-add-spi-override-to-merus-amp-overlay.patch"
SRC_URI += "file://0477-dt-Add-a-camera-regulator-node-to-all-downstream-Pi-.patch"
SRC_URI += "file://0478-dtoverlays-Update-sensor-overlays-to-use-cam1_reg-wh.patch"
SRC_URI += "file://0479-overlays-seeed-can-fd-hat-clarify-how-to-identify-HA.patch"
SRC_URI += "file://0480-SQUASH-Revert-overlays-Make-the-i2c-gpio-overlay-saf.patch"
SRC_URI += "file://0481-SQUASH-Revert-overlays-Fix-dtc-warnings-in-i2c-gpio.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0482-vc4-Correct-lbm-size-and-calculation.patch"

SRC_URI += "file://0483-vc4-Correct-POS1_SCL-for-hvs5.patch"
SRC_URI += "file://0484-configs-Enable-BCM2835-thermal-driver-in-kernel8.patch"
SRC_URI += "file://0485-uapi-bcm2835-isp-Add-colour-denoise-configuration.patch"
SRC_URI += "file://0486-staging-vc04_services-ISP-Add-colour-denoise-control.patch"
SRC_URI += "file://0487-configs-Add-CONFIG_NETFILTER_XT_MATCH_PHYSDEV-m.patch"
SRC_URI += "file://0488-configs-Add-CONFIG_USB_NET_AQC111-m.patch"
SRC_URI += "file://0489-dt-bindings-nvmem-Add-bindings-for-rmem-driver.patch"
SRC_URI += "file://0490-nvmem-Add-driver-to-expose-reserved-memory-as-nvmem.patch"
SRC_URI += "file://0491-ARM-dts-bcm2711-Add-reserved-memory-template-to-hold.patch"
SRC_URI += "file://0492-arm64-defconfig-Enable-nvmem-s-rmem-driver.patch"
SRC_URI += "file://0493-ARM-multi_v7_defconfig-Enable-nvmem-s-rmem-driver.patch"
SRC_URI += "file://0494-configs-Add-NVMEM_RMEM-m-for-2711.patch"
SRC_URI += "file://0495-configs-Add-CRYPTO_ADIANTUM-m.patch"
SRC_URI += "file://0496-spi-bcm2835-Workaround-fix-for-zero-length-transfers.patch"
SRC_URI += "file://0497-kbuild-Silence-unavoidable-dtc-overlay-warnings.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0498-drm-vc4-hvs-Fix-buffer-overflow-with-the-dlist-handl.patch"

SRC_URI += "file://0499-configs-Enable-CONFIG_MEDIA_CEC_RC.patch"
SRC_URI += "file://0500-Adds-the-DT-overlays-to-support-Hifiberry-AMP100.patch"
SRC_URI += "file://0501-Enhances-the-Hifiberry-DAC-driver-for-Hifiberry-AMP1.patch"
SRC_URI += "file://0502-ARM-dts-Declare-Pi400-and-CM4-have-no-audio-pins.patch"
SRC_URI += "file://0503-media-i2c-imx290-Replace-V4L2_CID_GAIN-with-V4L2_CID.patch"
SRC_URI += "file://0504-media-i2c-imx290-Fix-number-of-controls-in-v4l2_ctrl.patch"
SRC_URI += "file://0505-i2c-bcm2835-Handle-untimely-DONE-signal.patch"
SRC_URI += "file://0506-configs-Add-MICREL_PHY-y.patch"

# The following reverts patch 0452, which does not apply on the WR kernel
#SRC_URI += "file://0507-Revert-drm-vc4-hdmi-Limit-the-BCM2711-to-the-max-wit.patch"

# The following patch and 0520 are no longer needed since RCPL 4
#SRC_URI += "file://0508-Revert-vc4_hdmi-Move-hdmi-reset-to-bind.patch"

# The following patches revert patches 0325, 0326, 0336 and 0369 which don't
# apply on the WR kernel anyway
#SRC_URI += "file://0509-Revert-drm-vc4-Reading-the-hotplug-register-is-only-.patch"
#SRC_URI += "file://0510-Revert-vc4-cec-Restore-cec-physical-address-on-recon.patch"
#SRC_URI += "file://0511-Revert-vc4_hdmi-Remove-cec_available-flag-as-always-.patch"
#SRC_URI += "file://0512-Revert-vc4_hdmi-Adjust-CEC-ref-clock-based-on-its-in.patch"

SRC_URI += "file://0513-Revert-vc4_hdmi-Make-irq-shared.patch"
SRC_URI += "file://0514-Revert-vc4_hdmi_regs-Make-interrupt-mask-variant-spe.patch"
SRC_URI += "file://0515-Revert-vc4_hdmi_regs-Add-Intr2-register-block.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0516-Revert-vc4_hdmi-Fix-register-offset-when-sending-lon.patch"

SRC_URI += "file://0517-Revert-vc4_hdmi-BCM2835-requires-a-fixed-hsm-clock-f.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0518-Revert-vc4_hdmi-Fix-up-CEC-registers.patch"

SRC_URI += "file://0519-ARM-bcm-Select-BRCMSTB_L2_IRQ-for-bcm2835.patch"

# The following patch and 0508 are no longer needed since RCPL 4
#SRC_URI += "file://0520-drm-vc4-hdmi-Move-hdmi-reset-to-bind.patch"

# The following five patches are already included in the WR kernel
#SRC_URI += "file://0521-drm-vc4-hdmi-Fix-register-offset-with-longer-CEC-mes.patch"
#SRC_URI += "file://0522-drm-vc4-hdmi-Fix-up-CEC-registers.patch"
#SRC_URI += "file://0523-drm-vc4-hdmi-Restore-cec-physical-address-on-reconne.patch"
#SRC_URI += "file://0524-drm-vc4-hdmi-Compute-the-CEC-clock-divider-from-the-.patch"
#SRC_URI += "file://0525-drm-vc4-hdmi-Update-the-CEC-clock-divider-on-HSM-rat.patch"

SRC_URI += "file://0526-drm-vc4-hdmi-Introduce-a-CEC-clock.patch"
SRC_URI += "file://0527-drm-vc4-hdmi-Split-the-interrupt-handlers.patch"
SRC_URI += "file://0528-drm-vc4-hdmi-Support-BCM2711-CEC-interrupt-setup.patch"
SRC_URI += "file://0529-drm-vc4-hdmi-Remove-cec_available-flag.patch"
SRC_URI += "file://0530-drm-vc4-hdmi-Don-t-register-the-CEC-adapter-if-there.patch"
SRC_URI += "file://0531-dt-binding-display-bcm2711-hdmi-Add-CEC-and-hotplug-.patch"
SRC_URI += "file://0532-ARM-dts-bcm2711-Add-the-BSC-interrupt-controller.patch"
SRC_URI += "file://0533-ARM-dts-bcm2711-Add-the-CEC-interrupt-controller.patch"
SRC_URI += "file://0534-bcm2711-Disable-bsc_intr-and-aon_intr-by-default-and.patch"
SRC_URI += "file://0535-drm-vc4-hdmi-Limit-the-BCM2711-to-the-max-without-sc.patch"
SRC_URI += "file://0536-bcm2711-Remove-old-GIC-interrupt.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0537-w1-w1_therm-Fix-conversion-result-for-negative-tempe.patch"

SRC_URI += "file://0538-staging-bcm2835-camera-Fix-the-cherry-pick-of-AWB-Gr.patch"
SRC_URI += "file://0539-Overlays-for-PiFi-Mini-amp.patch"
SRC_URI += "file://0540-Added-PiFi-Mini-to-rpi-simple-soundcard.c.patch"
SRC_URI += "file://0541-bcm2835-isp-Allow-formats-with-different-colour-spac.patch"
SRC_URI += "file://0542-Hifiberry-DAC-ADC-Pro-fix-for-the-PLL-when-changing-.patch"
SRC_URI += "file://0543-Fixed-picture-line-bug-in-all-ov9281-modes.patch"
SRC_URI += "file://0544-Added-hflip-and-vflip-controls-to-ov9281.patch"
SRC_URI += "file://0545-Partial-revert-bcm2711-Disable-bsc_intr-and-aon_intr.patch"
SRC_URI += "file://0546-Revert-ARM-dts-bcm2711-Add-the-BSC-interrupt-control.patch"
SRC_URI += "file://0547-gpio-fsm-Rename-num-soft-gpios-to-avoid-warning.patch"
SRC_URI += "file://0548-overlays-Rename-gpio-fsm-property-num-soft-gpios.patch"
SRC_URI += "file://0549-drm-fix-HDR-static-metadata-type-field-numbering.patch"
SRC_URI += "file://0550-drm-vc4-Add-HDR-metadata-property-to-the-VC5-HDMI-co.patch"
SRC_URI += "file://0551-drm-vc4-Add-connector-check-to-trigger-mode_change-w.patch"
SRC_URI += "file://0552-staging-rpivid-Fix-crash-when-CMA-alloc-fails.patch"
SRC_URI += "file://0553-dt-Add-option-for-dpi-without-DE-and-PCLK-for-VGA666.patch"
SRC_URI += "file://0554-defconfigs-Add-DRM_DISPLAY_CONNECTOR-and-DRM_SIMPLE_.patch"
SRC_URI += "file://0555-dtoverlays-Add-an-overlay-for-the-VGA666-when-used-w.patch"
SRC_URI += "file://0556-drm-vc4-Change-the-default-DPI-format-to-being-18bpp.patch"
SRC_URI += "file://0557-gpio-fsm-Show-state-info-in-sys-class-gpio-fsm.patch"
SRC_URI += "file://0558-gpio-fsm-Fix-shutdown-timeout-handling.patch"
SRC_URI += "file://0559-overlays-fsm-demo-Ensure-all-LEDs-are-turned-off.patch"
SRC_URI += "file://0560-configs-Add-various-missing-IPV6-modules.patch"
SRC_URI += "file://0561-media-i2c-imx477-Remove-auto-frame-length-adjusting.patch"
SRC_URI += "file://0562-media-i2c-imx477-Add-very-long-exposure-control-to-t.patch"
SRC_URI += "file://0563-media-i2c-imx290-Fix-up-exposure-calcuations-and-ran.patch"
SRC_URI += "file://0564-media-i2c-imx290-Handle-exposure-correctly-when-vbla.patch"
SRC_URI += "file://0565-DAC-overlays-4154.patch"
SRC_URI += "file://0566-configs-Change-CONFIG_BLK_DEV_NVME-y-for-2711.patch"
SRC_URI += "file://0567-media-i2c-imx477-Fix-crop-height-for-2028x1080-mode.patch"
SRC_URI += "file://0568-media-i2c-imx477-Replace-existing-1012x760-mode.patch"
SRC_URI += "file://0569-media-i2c-imx477-Remove-internal-v4l2_mbus_framefmt-.patch"
SRC_URI += "file://0570-media-i2c-imx477-Remove-unused-function-parameter.patch"
SRC_URI += "file://0571-overlays-i2c-rtc-Add-the-Dallas-DS1340.patch"
SRC_URI += "file://0572-overlays-Update-the-upstream-overlay.patch"
SRC_URI += "file://0573-Revert-Bluetooth-Always-request-for-user-confirmatio.patch"
SRC_URI += "file://0574-Revert-Bluetooth-Always-request-for-user-confirmatio.patch"
SRC_URI += "file://0575-media-bcm2835-unicam-Fix-bug-in-buffer-swapping-logi.patch"
SRC_URI += "file://0576-Assign-crypto-aliases-to-different-AES-implementatio.patch"
SRC_URI += "file://0577-overlays-Improve-the-i2c-rtc-i2c_csi_dsi-option.patch"
SRC_URI += "file://0578-configs-Add-CONFIG_RTS_HCTOSYS-y.patch"
SRC_URI += "file://0579-media-v4l2_m2m-In-buffered-mode-run-jobs-if-either-p.patch"
SRC_URI += "file://0580-staging-bcm2835-codec-Correct-logging-of-size_t-to-z.patch"
SRC_URI += "file://0581-staging-bcm2835-codec-Add-support-for-pixel-aspect-r.patch"
SRC_URI += "file://0582-staging-bcm2835-codec-Implement-additional-g_selecti.patch"
SRC_URI += "file://0583-staging-bcm2835-codec-Add-VC-1-support.patch"
SRC_URI += "file://0584-vc4-drm-Avoid-full-hdmi-audio-fifo-writes.patch"
SRC_URI += "file://0585-vc4-drm-Increase-hdmi-audio-axi-priority-to-avoid-lo.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0586-drm-vc4-crtc-Reduce-PV-fifo-threshold-on-hvs4.patch"

SRC_URI += "file://0587-overlays-gpio-led-new-overlay.patch"
SRC_URI += "file://0588-overlays-Add-pcie-32bit-dma-overlay.patch"
SRC_URI += "file://0589-Revert-i2c-bcm2835-Handle-untimely-DONE-signal.patch"
SRC_URI += "file://0590-ARM-dts-bcm2711-Add-aliases-for-additional-SPIs.patch"
SRC_URI += "file://0591-Make-rpi-poe-fan-less-noisy-in-cool-environments.patch"
SRC_URI += "file://0592-vc4-drm-Fix-source-offsets-with-DRM_FORMAT_P030.patch"
SRC_URI += "file://0593-vc4-drm-vc4_plane-Remove-subpixel-positioning-check.patch"
SRC_URI += "file://0594-clk-raspberrypi-Also-support-HEVC-clock.patch"
SRC_URI += "file://0595-dt-Switch-hevc-clock-from-fixed-to-firmware-driver.patch"
SRC_URI += "file://0596-rpivid-Request-maximum-hevc-clock.patch"
SRC_URI += "file://0597-staging-bcm2835-camera-Add-support-for-DMABUFs.patch"
SRC_URI += "file://0598-staging-fbtft-Add-minipitft13-variant.patch"
SRC_URI += "file://0599-overlays-Add-minipitft13-overlay.patch"
SRC_URI += "file://0600-overlays-ghost-amp-Minor-tweaks.patch"
SRC_URI += "file://0601-overlays-Add-README-entry-for-minipitft13.patch"
SRC_URI += "file://0602-ARM-dts-update-bcm2711-rpi-cm4.dts-and-400.patch"
SRC_URI += "file://0603-Revert-usb-xhci-Disable-the-XHCI-5-second-timeout.patch"
SRC_URI += "file://0604-vc4-drm-SQUASH-Fix-source-offsets-with-DRM_FORMAT_P0.patch"
SRC_URI += "file://0605-dwc-otg-fix-clang-Wignored-attributes-warning.patch"
SRC_URI += "file://0606-dwc-otg-fix-clang-Wsometimes-uninitialized-warning.patch"
SRC_URI += "file://0607-dwc-otg-fix-clang-Wpointer-bool-conversion-warning.patch"
SRC_URI += "file://0608-Update-Allo-Piano-Dac-Driver.patch"

# The following three patches are already included in the WR kernel
#SRC_URI += "file://0609-sc16is7xx-Defer-probe-if-device-read-fails.patch"
#SRC_URI += "file://0610-ASoC-tlv320aic32x4-Register-clocks-before-registerin.patch"
#SRC_URI += "file://0611-ASoC-tlv320aic32x4-Increase-maximum-register-in-regm.patch"

SRC_URI += "file://0612-drm-connector-Create-a-helper-to-attach-the-hdr_outp.patch"
SRC_URI += "file://0613-drm-connector-Add-helper-to-compare-HDR-metadata.patch"
SRC_URI += "file://0614-drm-vc4-Use-the-new-helpers.patch"
SRC_URI += "file://0615-drm-connector-Add-a-helper-to-attach-the-colorspace-.patch"
SRC_URI += "file://0616-drm-vc4-hdmi-Signal-the-proper-colorimetry-info-in-t.patch"
SRC_URI += "file://0617-staging-vcsm-cma-Fix-memory-leak-from-not-detaching-.patch"
SRC_URI += "file://0618-vc4-kms-vc4_plane-Support-2020-colourspace-for-yuv-p.patch"
SRC_URI += "file://0619-sound-usb-add-device-quirks-for-A4Tech-FHD-1080p-web.patch"
SRC_URI += "file://0620-sound-usb-call-usb_autopm_get_interface-for-devices-.patch"
SRC_URI += "file://0621-overlays-ghost-amp-Add-DAC-mute-control.patch"
SRC_URI += "file://0622-clk-Introduce-a-clock-request-API.patch"
SRC_URI += "file://0623-drm-vc4-hdmi-Convert-to-the-new-clock-request-API.patch"
SRC_URI += "file://0624-drm-vc4-hdmi-Convert-to-the-new-clock-request-API.patch"
SRC_URI += "file://0625-bcm2835-unicam-Switch-to-new-clock-api.patch"
SRC_URI += "file://0626-rpivid-Switch-to-new-clock-api.patch"
SRC_URI += "file://0627-net-usb-r8152-Provide-missing-documentation-for-some.patch"
SRC_URI += "file://0628-net-usb-r8152-Fix-a-couple-of-spelling-errors-in-fw_.patch"
SRC_URI += "file://0629-net-usb-r8153_ecm-support-ECM-mode-for-RTL8153.patch"
SRC_URI += "file://0630-net-usb-r8152-use-new-tasklet-API.patch"
SRC_URI += "file://0631-r8152-replace-several-functions-about-phy-patch-requ.patch"
SRC_URI += "file://0632-r8152-adjust-the-flow-of-power-cut-for-RTL8153B.patch"
SRC_URI += "file://0633-r8152-enable-U1-U2-for-USB_SPEED_SUPER.patch"
SRC_URI += "file://0634-r8152-check-if-the-pointer-of-the-function-exists.patch"
SRC_URI += "file://0635-r8152-replace-netif_err-with-dev_err.patch"
SRC_URI += "file://0636-r8152-spilt-rtl_set_eee_plus-and-r8153b_green_en.patch"
SRC_URI += "file://0637-r8152-set-inter-fram-gap-time-depending-on-speed.patch"
SRC_URI += "file://0638-r8152-adjust-rtl8152_check_firmware-function.patch"
SRC_URI += "file://0639-r8152-add-help-function-to-change-mtu.patch"
SRC_URI += "file://0640-r8152-support-new-chips.patch"
SRC_URI += "file://0641-r8152-support-PHY-firmware-for-RTL8156-series.patch"
SRC_URI += "file://0642-r8152-search-the-configuration-of-vendor-mode.patch"
SRC_URI += "file://0643-rpivid-Only-clk_request_done-once.patch"
SRC_URI += "file://0644-dwc_otg-fix-an-undeclared-variable.patch"
SRC_URI += "file://0645-Revert-drm-vc4-Add-configuration-for-BCM2711-DSI1.patch"
SRC_URI += "file://0646-Revert-drm-vc4-Add-support-for-DSI0.patch"
SRC_URI += "file://0647-drm-vc4-drv-Remove-the-DSI-pointer-in-vc4_drv.patch"
SRC_URI += "file://0648-drm-vc4-dsi-Use-snprintf-for-the-PHY-clocks-instead-.patch"
SRC_URI += "file://0649-drm-vc4-dsi-Introduce-a-variant-structure.patch"
SRC_URI += "file://0650-drm-vc4-dsi-Add-support-for-DSI0.patch"
SRC_URI += "file://0651-drm-vc4-dsi-Add-configuration-for-BCM2711-DSI1.patch"
SRC_URI += "file://0652-drm-vc4-Correct-pixel-order-for-DSI0.patch"
SRC_URI += "file://0653-drm-vc4-Register-dsi0-as-the-correct-vc4-encoder-typ.patch"
SRC_URI += "file://0654-drm-vc4-Fix-dsi0-interrupt-support.patch"
SRC_URI += "file://0655-drm-vc4-Add-correct-stop-condition-to-vc4_dsi_encode.patch"
SRC_URI += "file://0656-drm-atomic-Don-t-fixup-modes-that-haven-t-been-reset.patch"
SRC_URI += "file://0657-drm-panel-jdi-lt070me05000-Use-gpiod_set_value_cansl.patch"
SRC_URI += "file://0658-defconfigs-Add-PANEL_JDI_LT070ME05000-DSI-panel.patch"
SRC_URI += "file://0659-dtoverlays-Add-overlays-for-JDI-LT070ME05000-1200x19.patch"
SRC_URI += "file://0660-clk-requests-Ignore-if-the-pointer-is-null.patch"

# The following patch is no longer needed since RCPL 4
#SRC_URI += "file://0661-drm-vc4-txp-Properly-set-the-possible_crtcs-mask.patch"

SRC_URI += "file://0662-drm-vc4-crtc-Skip-the-TXP.patch"
SRC_URI += "file://0663-drm-vc4-Rework-the-encoder-retrieval-code.patch"
SRC_URI += "file://0664-drm-vc4-hdmi-Prevent-clock-unbalance.patch"
SRC_URI += "file://0665-drm-vc4-hvs-Make-the-HVS-bind-first.patch"
SRC_URI += "file://0666-drm-vc4-hdmi-Properly-compute-the-BVB-clock-rate.patch"
SRC_URI += "file://0667-drm-vc4-hdmi-Check-and-warn-if-we-can-t-reach-4kp60-.patch"
SRC_URI += "file://0668-drm-vc4-hdmi-Enable-the-scrambler.patch"
SRC_URI += "file://0669-drm-vc4-hdmi-Raise-the-maximum-clock-rate.patch"
SRC_URI += "file://0670-vc4-drm-hdmi-Handle-case-when-bvb-clock-is-null.patch"
SRC_URI += "file://0671-overlays-spi-rtc-Add-ds3232-and-ds3234.patch"
SRC_URI += "file://0672-drm-vc4-Fix-VEC-address-for-BCM2711-in-the-devicetre.patch"

# The following patch is no longer needed since RCPL 4
#SRC_URI += "file://0673-drm-vc4-Fix-clock-source-for-VEC-PixelValve-on-BCM27.patch"

SRC_URI += "file://0674-drm-vc4-Separate-VEC-compatible-variants.patch"
SRC_URI += "file://0675-configs-Enable-ATA-and-AHCI-for-SATA-drive-support.patch"
SRC_URI += "file://0676-clk-requests-Dereference-the-request-pointer-after-t.patch"
SRC_URI += "file://0677-staging-bcm2835-codec-Fix-support-for-levels-4.1-and.patch"
SRC_URI += "file://0678-staging-bcm2835-codec-Set-the-colourspace-appropriat.patch"
SRC_URI += "file://0679-staging-bcm2835-codec-Pass-corrupt-frame-flag.patch"
SRC_URI += "file://0680-staging-bcm2835-camera-Add-support-for-H264-levels-4.patch"
SRC_URI += "file://0681-staging-bcm2835-codec-Do-not-update-crop-from-S_FMT-.patch"
SRC_URI += "file://0682-staging-bcm2835-isp-Fix-compiler-warning.patch"
SRC_URI += "file://0683-overlays-Allow-multiple-gpio-shutdown-instances.patch"
SRC_URI += "file://0684-overlays-README-improve-the-gpio-poweroff-guide.patch"
SRC_URI += "file://0685-SQUASH-overlays-Fix-typo-in-README.patch"
SRC_URI += "file://0686-gpio-poweroff-Remember-the-old-poweroff-handler.patch"
SRC_URI += "file://0687-drm-vc4-Allow-DBLCLK-modes-even-if-horz-timing-is-od.patch"
SRC_URI += "file://0688-overlays-Add-ugreen-dabboard-overlay.patch"
SRC_URI += "file://0689-ARM-dts-bcm2711-rpi-400-Limit-MDIO-clock-speed.patch"
SRC_URI += "file://0690-spi-bcm2835-Increase-the-CS-limit-to-24.patch"
SRC_URI += "file://0691-configs-Regenerate-defconfigs.patch"
SRC_URI += "file://0692-configs-add-CONFIG_QCA7000_UART-m-4322.patch"

# The following patch is already included from RCPL 3
#SRC_URI += "file://0693-usb-dwc2-Fix-gadget-DMA-unmap-direction.patch"

SRC_URI += "file://0694-clk-Always-clamp-the-rounded-rate.patch"
SRC_URI += "file://0695-Revert-drm-vc4-Rework-the-encoder-retrieval-code.patch"
SRC_URI += "file://0696-drm-vc4-crtc-Pass-the-drm_atomic_state-to-config_pv.patch"
SRC_URI += "file://0697-drm-vc4-crtc-Fix-vc4_get_crtc_encoder-logic.patch"
SRC_URI += "file://0698-drm-vc4-crtc-Lookup-the-encoder-from-the-register-at.patch"

# The following patch is not needed since RCPL 4
#SRC_URI += "file://0699-drm-vc4-hdmi-Switch-to-pm_runtime_resume_and_get.patch"

SRC_URI += "file://0700-drm-vc4-hdmi-Make-sure-the-controller-is-powered-in-.patch"
SRC_URI += "file://0701-drm-vc4-hdmi-Simplify-the-connector-state-retrieval.patch"
SRC_URI += "file://0702-drm-vc4-hdmi-Rely-on-interrupts-to-handle-hotplug.patch"
SRC_URI += "file://0703-drm-vc4-hdmi-Add-a-workqueue-to-set-scrambling.patch"
SRC_URI += "file://0704-vc4-drm-hdmi-Fix-missing-declaration.patch"
SRC_URI += "file://0705-overlays-merus-amp-remove-spi-override.patch"
SRC_URI += "file://0706-configs-Add-NF_LOG_ARP-m-and-NF_LOG_NETDEV-m.patch"
SRC_URI += "file://0707-media-i2c-ov5647-Correct-pixel-array-offset.patch"
SRC_URI += "file://0708-media-i2c-ov5647-Correct-minimum-VBLANK-value.patch"
SRC_URI += "file://0709-media-i2c-ov5647-Fix-v4l2-compliance-failure-subscri.patch"
SRC_URI += "file://0710-dtoverlays-Add-pinctrl-names-to-i2c0-overlay.patch"
SRC_URI += "file://0711-dtoverlays-Update-__symbols__-i2c0-from-i2c0-overlay.patch"

# The following patch is already included in the WR kernel
#SRC_URI += "file://0712-media-v4l2-ctrls.c-fix-race-condition-in-hdl-request.patch"

SRC_URI += "file://0713-media-rpivid-Remove-the-need-to-have-num_entry_point.patch"
SRC_URI += "file://0714-media-rpivid-Convert-to-MPLANE.patch"
SRC_URI += "file://0715-media-rpivid-Add-an-enable-count-to-irq-claim-Qs.patch"
SRC_URI += "file://0716-RFC-media-Add-media_request_-pin-unpin-API.patch"
SRC_URI += "file://0717-media-rpivid-Add-a-Pass0-to-accumulate-slices-and-re.patch"
SRC_URI += "file://0718-Revert-media-v4l2-mem2mem-allow-request-job-buffer-p.patch"
SRC_URI += "file://0719-media-rpivid-Map-cmd-buffer-directly.patch"
SRC_URI += "file://0720-media-rpivid-Improve-values-returned-when-setting-ou.patch"
SRC_URI += "file://0721-media-rpivid-Improve-stream_on-off-conformance-clock.patch"
SRC_URI += "file://0722-media-rpivid-Improve-SPS-PPS-error-handling-validati.patch"
SRC_URI += "file://0723-Add-CAN_J1939-as-module-to-default-build-configs-434.patch"
